<?php

require_once 'Animal.php';

class Mamifero extends Animal
{

    private $numeroTetas;

    public function setNumeroTetas($tetas) {
        $this->numeroTetas = $tetas;
    }

    public function setDataNascimento($data)
    {
        parent::setDataNascimento($data); // TODO: Change the autogenerated stub
    }

    public function nascer() {
        $this->setDataNascimento(date('dd/MM/yy'));
    }
}